CREATE TABLE `movies` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`imdb_id` integer NOT NULL UNIQUE,
	`title` text NOT NULL,
	`type` text NOT NULL,
	`plot` text,
	`fullplot` text,
	`poster` text,
	`rated` text,
	`runtime` integer,
	`genres` text NOT NULL,
	`cast_members` text NOT NULL,
	`directors` text NOT NULL,
	`writers` text NOT NULL,
	`countries` text NOT NULL,
	`languages` text NOT NULL,
	`imdb_rating` real,
	`imdb_votes` integer,
	`metacritic` integer,
	`awards_wins` integer DEFAULT 0 NOT NULL,
	`awards_nominations` integer DEFAULT 0 NOT NULL,
	`awards_text` text,
	`num_mflix_comments` integer DEFAULT 0 NOT NULL,
	`plot_embedding` blob,
	`ingested_at` text DEFAULT (current_timestamp) NOT NULL
);
